### PR TITLE
Minor typo fixes 

### PR DESCRIPTION
**Pull request by AmarkovicC4**

### CODE REVIEW

**Comment by jmcgeeverC4** [comment]
Thanks for the corrections.
Jim

**Comment by jmcgeeverC4** [comment]
For some reason I was unable to merge your changes through github. I corrected them manually in the docs and you should see them in the Slate output. Thanks again . Jim

**Comment by AmarkovicC4** [comment]
Hello,

Sorry for the late reply.
Thank you so much for your effort. I will push more changes in the next few days. Please let me know if you have any problem regarding commit again. I would like to solve any potential issue with my GitHub account ( it is a new one, may be some incorrect settings or similar ).

Best regards
________________________________

**Comment by jmcgeeverC4** [comment]
I think the issue was on my end actually. I’ll let you know on the next pull request.
Thank you for suggesting changes to the docs.

Jim

**Pull request closed without merging**
